model: 'geoan'
n_geoab: 9
#c_geoan: 60
c_geoan: 120
c_in: 5
# window_sizes: [ 2,4,13 ]
window_sizes: [ 2, 4, 8 ]
num_heads: 8
down_sample: 8
r_expand: 4
fp: 32
loss: 'nn.L1Loss()'
# loss: 'nn.SmoothL1Loss()'
#loss: 'LatitudeLoss()'
optimizer: 'AdamW'
pretrain:
resume:
batch_size: 4
balanced_gpu0: -1
epochs: 300
#lr: 0.0002
lr: 0.0001
decays: [ 50,80,90,95 ]
gamma: 0.1
test_every: 1
log_lines: 100
log_path: "./experiments"
log_name:
cloudlog: off
repeat: 1
augment: 'off'
# produce
#test_data_path: './proc/test_data/'
model_path: '/home/czx/pycode/Pansharpening/Pansharpening/experiments/geoan-2025-0420-2310-2087_good/models/model_88.pt'
# model_path: './experiments/testmodel/6h_523.pt'
save_path: "./proc"

## hardware specification
# specify the GPUs you want to use. [0] means using the first GPU. [1,3] means using second and fourth GPU
gpu_ids: [ 0, 1 ,2, 3 ]
#gpu_ids: [ 0 ]
threads: 4
## data specification
# the path train and test dateset. You can download the dataset in this project
train_data_path: '/mnt/data1/czx/Pansharpening/GF2v2/Train'
valid_data_path: '/mnt/data1/czx/Pansharpening/GF2v2/Valid'
test_data_path: '/mnt/data1/czx/Pansharpening/GF2/Test'